# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMPiplelin-conn'
    subscriptionId: 'c250d75b-15c1-4224-9c6c-8c6b2542955b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARMPiplelin-rg'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/theseha/ARMPiplelin-repo/main/create_web_app/azuredeploy.json'
    overrideParameters: '-projectName ARMpiplelinProj'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
